---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-prepper.configName" . }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
data:
  data-prepper-config.yaml: |
    {{- toYaml .Values.dataPrepperConfig | nindent 6 }}
---
{{- if not .Values.pipeline.mountFromSecret.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-prepper.pipelineConfigName" . }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
data:
  pipelines.yaml: |
    {{- toYaml .Values.pipeline.config | nindent 6 }}
{{- end }}
