---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-prepper.fullname" . }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "data-prepper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "data-prepper.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.pipelineConfig.interpolateFromSecret.enabled }}
      initContainers:
      - name: config-interpolator
        image: dibi/envsubst:1
        envFrom:
        - secretRef:
            name: {{ .Values.pipelineConfig.interpolateFromSecret.secretName | default ( include "data-prepper.secretName" . ) }}
        volumeMounts:
        - name: config
          mountPath: /workdir
        - name: data-prepper-pipelines
          mountPath: /processed
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "data-prepper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          {{- if .Values.javaDebug }}
            - name: JAVA_OPTS
              value: -Dlog4j2.debug=true
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: TCP
          {{- end }}
            - name: server
              containerPort: {{ (.Values.dataPrepperConfig).serverPort | default 4900 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /list
              port: server
              {{- if not ( empty (.Values.dataPrepperConfig).ssl ) }}
              scheme: HTTPS
              {{- end }}
            periodSeconds: 10
            initialDelaySeconds: 2
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /list
              port: server
              {{- if not ( empty (.Values.dataPrepperConfig).ssl ) }}
              scheme: HTTPS
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data-prepper-config
              mountPath: /usr/share/data-prepper/config
              readOnly: true
            - name: data-prepper-pipelines
              mountPath: /usr/share/data-prepper/pipelines
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- if .Values.pipelineConfig.interpolateFromSecret.enabled }}
        - name: config
          secret:
          {{- if (.Values.pipelineConfig.interpolateFromSecret).secretName }}
            secretName: {{ .Values.pipelineConfig.interpolateFromSecret.secretName }}
          {{- else }}
            secretName: {{ include "data-prepper.secretName" . }}
          {{- end }}
      {{- end }}
        - name: data-prepper-config
          configMap:
            name: {{ include "data-prepper.configName" . }}
        - name: data-prepper-pipelines
          {{- if .Values.pipelineConfig.interpolateFromSecret.enabled }}
          emptyDir: {}
          {{- else if (.Values.pipelineConfig.mountFromSecret).enabled }}
          secret:
            secretName: {{ .Values.pipelineConfig.mountFromSecret.secretName | default (include "data-prepper.secretName" .) }}
          {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
