---
{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-prepper.secretName" . }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
{{- with .Values.secret }}
data:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
