{{- if not (.Values.pipelineConfig.fromSecret.enabled) }}
apiVersion: v1
data:
  pipelines.yaml: {{ toYaml .Values.pipelineConfig | b64enc }}
kind: Secret
metadata:
  name: {{ include "data-prepper.configName" . }}
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
{{- end }}
